// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: github.com/openconfig/gnsi/acctz/acctz.proto

package acctz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionInfo_SessionStatus int32

const (
	SessionInfo_SESSION_STATUS_UNSPECIFIED SessionInfo_SessionStatus = 0
	SessionInfo_SESSION_STATUS_LOGIN       SessionInfo_SessionStatus = 1
	SessionInfo_SESSION_STATUS_LOGOUT      SessionInfo_SessionStatus = 2
	SessionInfo_SESSION_STATUS_ONCE        SessionInfo_SessionStatus = 3
	SessionInfo_SESSION_STATUS_ENABLE      SessionInfo_SessionStatus = 4
	SessionInfo_SESSION_STATUS_IDLE        SessionInfo_SessionStatus = 5
	SessionInfo_SESSION_STATUS_OPERATION   SessionInfo_SessionStatus = 6
)

// Enum value maps for SessionInfo_SessionStatus.
var (
	SessionInfo_SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_LOGIN",
		2: "SESSION_STATUS_LOGOUT",
		3: "SESSION_STATUS_ONCE",
		4: "SESSION_STATUS_ENABLE",
		5: "SESSION_STATUS_IDLE",
		6: "SESSION_STATUS_OPERATION",
	}
	SessionInfo_SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_LOGIN":       1,
		"SESSION_STATUS_LOGOUT":      2,
		"SESSION_STATUS_ONCE":        3,
		"SESSION_STATUS_ENABLE":      4,
		"SESSION_STATUS_IDLE":        5,
		"SESSION_STATUS_OPERATION":   6,
	}
)

func (x SessionInfo_SessionStatus) Enum() *SessionInfo_SessionStatus {
	p := new(SessionInfo_SessionStatus)
	*p = x
	return p
}

func (x SessionInfo_SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionInfo_SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[0].Descriptor()
}

func (SessionInfo_SessionStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[0]
}

func (x SessionInfo_SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionInfo_SessionStatus.Descriptor instead.
func (SessionInfo_SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{0, 0}
}

type AuthDetail_AuthenStatus int32

const (
	AuthDetail_AUTHEN_STATUS_UNSPECIFIED AuthDetail_AuthenStatus = 0
	AuthDetail_AUTHEN_STATUS_PERMIT      AuthDetail_AuthenStatus = 1
	AuthDetail_AUTHEN_STATUS_DENY        AuthDetail_AuthenStatus = 2
)

// Enum value maps for AuthDetail_AuthenStatus.
var (
	AuthDetail_AuthenStatus_name = map[int32]string{
		0: "AUTHEN_STATUS_UNSPECIFIED",
		1: "AUTHEN_STATUS_PERMIT",
		2: "AUTHEN_STATUS_DENY",
	}
	AuthDetail_AuthenStatus_value = map[string]int32{
		"AUTHEN_STATUS_UNSPECIFIED": 0,
		"AUTHEN_STATUS_PERMIT":      1,
		"AUTHEN_STATUS_DENY":        2,
	}
)

func (x AuthDetail_AuthenStatus) Enum() *AuthDetail_AuthenStatus {
	p := new(AuthDetail_AuthenStatus)
	*p = x
	return p
}

func (x AuthDetail_AuthenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthDetail_AuthenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[1].Descriptor()
}

func (AuthDetail_AuthenStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[1]
}

func (x AuthDetail_AuthenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthDetail_AuthenStatus.Descriptor instead.
func (AuthDetail_AuthenStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{2, 0}
}

type AuthnDetail_AuthnType int32

const (
	AuthnDetail_AUTHN_TYPE_UNSPECIFIED AuthnDetail_AuthnType = 0
	AuthnDetail_AUTHN_TYPE_NONE        AuthnDetail_AuthnType = 1
	AuthnDetail_AUTHN_TYPE_PASSWORD    AuthnDetail_AuthnType = 2
	AuthnDetail_AUTHN_TYPE_SSHKEY      AuthnDetail_AuthnType = 3
	AuthnDetail_AUTHN_TYPE_SSHCERT     AuthnDetail_AuthnType = 4
	AuthnDetail_AUTHN_TYPE_TLSCERT     AuthnDetail_AuthnType = 5
	AuthnDetail_AUTHN_TYPE_PAP         AuthnDetail_AuthnType = 6
	AuthnDetail_AUTHN_TYPE_CHAP        AuthnDetail_AuthnType = 7
)

// Enum value maps for AuthnDetail_AuthnType.
var (
	AuthnDetail_AuthnType_name = map[int32]string{
		0: "AUTHN_TYPE_UNSPECIFIED",
		1: "AUTHN_TYPE_NONE",
		2: "AUTHN_TYPE_PASSWORD",
		3: "AUTHN_TYPE_SSHKEY",
		4: "AUTHN_TYPE_SSHCERT",
		5: "AUTHN_TYPE_TLSCERT",
		6: "AUTHN_TYPE_PAP",
		7: "AUTHN_TYPE_CHAP",
	}
	AuthnDetail_AuthnType_value = map[string]int32{
		"AUTHN_TYPE_UNSPECIFIED": 0,
		"AUTHN_TYPE_NONE":        1,
		"AUTHN_TYPE_PASSWORD":    2,
		"AUTHN_TYPE_SSHKEY":      3,
		"AUTHN_TYPE_SSHCERT":     4,
		"AUTHN_TYPE_TLSCERT":     5,
		"AUTHN_TYPE_PAP":         6,
		"AUTHN_TYPE_CHAP":        7,
	}
)

func (x AuthnDetail_AuthnType) Enum() *AuthnDetail_AuthnType {
	p := new(AuthnDetail_AuthnType)
	*p = x
	return p
}

func (x AuthnDetail_AuthnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthnDetail_AuthnType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[2].Descriptor()
}

func (AuthnDetail_AuthnType) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[2]
}

func (x AuthnDetail_AuthnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthnDetail_AuthnType.Descriptor instead.
func (AuthnDetail_AuthnType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{3, 0}
}

type AuthnDetail_AuthnStatus int32

const (
	AuthnDetail_AUTHN_STATUS_UNSPECIFIED AuthnDetail_AuthnStatus = 0
	AuthnDetail_AUTHN_STATUS_SUCCESS     AuthnDetail_AuthnStatus = 1
	AuthnDetail_AUTHN_STATUS_FAIL        AuthnDetail_AuthnStatus = 2
	AuthnDetail_AUTHN_STATUS_ERROR       AuthnDetail_AuthnStatus = 3
)

// Enum value maps for AuthnDetail_AuthnStatus.
var (
	AuthnDetail_AuthnStatus_name = map[int32]string{
		0: "AUTHN_STATUS_UNSPECIFIED",
		1: "AUTHN_STATUS_SUCCESS",
		2: "AUTHN_STATUS_FAIL",
		3: "AUTHN_STATUS_ERROR",
	}
	AuthnDetail_AuthnStatus_value = map[string]int32{
		"AUTHN_STATUS_UNSPECIFIED": 0,
		"AUTHN_STATUS_SUCCESS":     1,
		"AUTHN_STATUS_FAIL":        2,
		"AUTHN_STATUS_ERROR":       3,
	}
)

func (x AuthnDetail_AuthnStatus) Enum() *AuthnDetail_AuthnStatus {
	p := new(AuthnDetail_AuthnStatus)
	*p = x
	return p
}

func (x AuthnDetail_AuthnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthnDetail_AuthnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[3].Descriptor()
}

func (AuthnDetail_AuthnStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[3]
}

func (x AuthnDetail_AuthnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthnDetail_AuthnStatus.Descriptor instead.
func (AuthnDetail_AuthnStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{3, 1}
}

type AuthzDetail_AuthzStatus int32

const (
	AuthzDetail_AUTHZ_STATUS_UNSPECIFIED AuthzDetail_AuthzStatus = 0
	AuthzDetail_AUTHZ_STATUS_PERMIT      AuthzDetail_AuthzStatus = 1
	AuthzDetail_AUTHZ_STATUS_DENY        AuthzDetail_AuthzStatus = 2
	AuthzDetail_AUTHZ_STATUS_ERROR       AuthzDetail_AuthzStatus = 3
)

// Enum value maps for AuthzDetail_AuthzStatus.
var (
	AuthzDetail_AuthzStatus_name = map[int32]string{
		0: "AUTHZ_STATUS_UNSPECIFIED",
		1: "AUTHZ_STATUS_PERMIT",
		2: "AUTHZ_STATUS_DENY",
		3: "AUTHZ_STATUS_ERROR",
	}
	AuthzDetail_AuthzStatus_value = map[string]int32{
		"AUTHZ_STATUS_UNSPECIFIED": 0,
		"AUTHZ_STATUS_PERMIT":      1,
		"AUTHZ_STATUS_DENY":        2,
		"AUTHZ_STATUS_ERROR":       3,
	}
)

func (x AuthzDetail_AuthzStatus) Enum() *AuthzDetail_AuthzStatus {
	p := new(AuthzDetail_AuthzStatus)
	*p = x
	return p
}

func (x AuthzDetail_AuthzStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthzDetail_AuthzStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[4].Descriptor()
}

func (AuthzDetail_AuthzStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[4]
}

func (x AuthzDetail_AuthzStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthzDetail_AuthzStatus.Descriptor instead.
func (AuthzDetail_AuthzStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{4, 0}
}

type CommandService_CmdServiceType int32

const (
	CommandService_CMD_SERVICE_TYPE_UNSPECIFIED CommandService_CmdServiceType = 0
	CommandService_CMD_SERVICE_TYPE_SHELL       CommandService_CmdServiceType = 1
	CommandService_CMD_SERVICE_TYPE_CLI         CommandService_CmdServiceType = 2
	CommandService_CMD_SERVICE_TYPE_WEBUI       CommandService_CmdServiceType = 3
	CommandService_CMD_SERVICE_TYPE_RESTCONF    CommandService_CmdServiceType = 4
	CommandService_CMD_SERVICE_TYPE_NETCONF     CommandService_CmdServiceType = 5
)

// Enum value maps for CommandService_CmdServiceType.
var (
	CommandService_CmdServiceType_name = map[int32]string{
		0: "CMD_SERVICE_TYPE_UNSPECIFIED",
		1: "CMD_SERVICE_TYPE_SHELL",
		2: "CMD_SERVICE_TYPE_CLI",
		3: "CMD_SERVICE_TYPE_WEBUI",
		4: "CMD_SERVICE_TYPE_RESTCONF",
		5: "CMD_SERVICE_TYPE_NETCONF",
	}
	CommandService_CmdServiceType_value = map[string]int32{
		"CMD_SERVICE_TYPE_UNSPECIFIED": 0,
		"CMD_SERVICE_TYPE_SHELL":       1,
		"CMD_SERVICE_TYPE_CLI":         2,
		"CMD_SERVICE_TYPE_WEBUI":       3,
		"CMD_SERVICE_TYPE_RESTCONF":    4,
		"CMD_SERVICE_TYPE_NETCONF":     5,
	}
)

func (x CommandService_CmdServiceType) Enum() *CommandService_CmdServiceType {
	p := new(CommandService_CmdServiceType)
	*p = x
	return p
}

func (x CommandService_CmdServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandService_CmdServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[5].Descriptor()
}

func (CommandService_CmdServiceType) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[5]
}

func (x CommandService_CmdServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandService_CmdServiceType.Descriptor instead.
func (CommandService_CmdServiceType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{5, 0}
}

type GrpcService_GrpcServiceType int32

const (
	GrpcService_GRPC_SERVICE_TYPE_UNSPECIFIED GrpcService_GrpcServiceType = 0
	GrpcService_GRPC_SERVICE_TYPE_GNMI        GrpcService_GrpcServiceType = 1
	GrpcService_GRPC_SERVICE_TYPE_GNOI        GrpcService_GrpcServiceType = 2
	GrpcService_GRPC_SERVICE_TYPE_GNSI        GrpcService_GrpcServiceType = 3
	GrpcService_GRPC_SERVICE_TYPE_GRIBI       GrpcService_GrpcServiceType = 4
	GrpcService_GRPC_SERVICE_TYPE_P4RT        GrpcService_GrpcServiceType = 5
)

// Enum value maps for GrpcService_GrpcServiceType.
var (
	GrpcService_GrpcServiceType_name = map[int32]string{
		0: "GRPC_SERVICE_TYPE_UNSPECIFIED",
		1: "GRPC_SERVICE_TYPE_GNMI",
		2: "GRPC_SERVICE_TYPE_GNOI",
		3: "GRPC_SERVICE_TYPE_GNSI",
		4: "GRPC_SERVICE_TYPE_GRIBI",
		5: "GRPC_SERVICE_TYPE_P4RT",
	}
	GrpcService_GrpcServiceType_value = map[string]int32{
		"GRPC_SERVICE_TYPE_UNSPECIFIED": 0,
		"GRPC_SERVICE_TYPE_GNMI":        1,
		"GRPC_SERVICE_TYPE_GNOI":        2,
		"GRPC_SERVICE_TYPE_GNSI":        3,
		"GRPC_SERVICE_TYPE_GRIBI":       4,
		"GRPC_SERVICE_TYPE_P4RT":        5,
	}
)

func (x GrpcService_GrpcServiceType) Enum() *GrpcService_GrpcServiceType {
	p := new(GrpcService_GrpcServiceType)
	*p = x
	return p
}

func (x GrpcService_GrpcServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrpcService_GrpcServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[6].Descriptor()
}

func (GrpcService_GrpcServiceType) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes[6]
}

func (x GrpcService_GrpcServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrpcService_GrpcServiceType.Descriptor instead.
func (GrpcService_GrpcServiceType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{6, 0}
}

type SessionInfo struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	LocalAddress  string                    `protobuf:"bytes,1,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	LocalPort     uint32                    `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteAddress string                    `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	RemotePort    uint32                    `protobuf:"varint,4,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	IpProto       uint32                    `protobuf:"varint,5,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	ChannelId     string                    `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Tty           string                    `protobuf:"bytes,7,opt,name=tty,proto3" json:"tty,omitempty"`
	Status        SessionInfo_SessionStatus `protobuf:"varint,8,opt,name=status,proto3,enum=gnsi.acctz.v1.SessionInfo_SessionStatus" json:"status,omitempty"`
	User          *UserDetail               `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	Authn         *AuthnDetail              `protobuf:"bytes,10,opt,name=authn,proto3" json:"authn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *SessionInfo) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *SessionInfo) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *SessionInfo) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *SessionInfo) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *SessionInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SessionInfo) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *SessionInfo) GetStatus() SessionInfo_SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionInfo_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionInfo) GetUser() *UserDetail {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SessionInfo) GetAuthn() *AuthnDetail {
	if x != nil {
		return x.Authn
	}
	return nil
}

type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	SshPrincipal  string                 `protobuf:"bytes,3,opt,name=ssh_principal,json=sshPrincipal,proto3" json:"ssh_principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetail) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserDetail) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserDetail) GetSshPrincipal() string {
	if x != nil {
		return x.SshPrincipal
	}
	return ""
}

type AuthDetail struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Identity       string                  `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	PrivilegeLevel uint32                  `protobuf:"varint,2,opt,name=privilege_level,json=privilegeLevel,proto3" json:"privilege_level,omitempty"`
	Status         AuthDetail_AuthenStatus `protobuf:"varint,3,opt,name=status,proto3,enum=gnsi.acctz.v1.AuthDetail_AuthenStatus" json:"status,omitempty"`
	DenyCause      string                  `protobuf:"bytes,4,opt,name=deny_cause,json=denyCause,proto3" json:"deny_cause,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthDetail) Reset() {
	*x = AuthDetail{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthDetail) ProtoMessage() {}

func (x *AuthDetail) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthDetail.ProtoReflect.Descriptor instead.
func (*AuthDetail) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{2}
}

func (x *AuthDetail) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *AuthDetail) GetPrivilegeLevel() uint32 {
	if x != nil {
		return x.PrivilegeLevel
	}
	return 0
}

func (x *AuthDetail) GetStatus() AuthDetail_AuthenStatus {
	if x != nil {
		return x.Status
	}
	return AuthDetail_AUTHEN_STATUS_UNSPECIFIED
}

func (x *AuthDetail) GetDenyCause() string {
	if x != nil {
		return x.DenyCause
	}
	return ""
}

type AuthnDetail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          AuthnDetail_AuthnType   `protobuf:"varint,1,opt,name=type,proto3,enum=gnsi.acctz.v1.AuthnDetail_AuthnType" json:"type,omitempty"`
	Status        AuthnDetail_AuthnStatus `protobuf:"varint,2,opt,name=status,proto3,enum=gnsi.acctz.v1.AuthnDetail_AuthnStatus" json:"status,omitempty"`
	Cause         string                  `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnDetail) Reset() {
	*x = AuthnDetail{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnDetail) ProtoMessage() {}

func (x *AuthnDetail) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnDetail.ProtoReflect.Descriptor instead.
func (*AuthnDetail) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{3}
}

func (x *AuthnDetail) GetType() AuthnDetail_AuthnType {
	if x != nil {
		return x.Type
	}
	return AuthnDetail_AUTHN_TYPE_UNSPECIFIED
}

func (x *AuthnDetail) GetStatus() AuthnDetail_AuthnStatus {
	if x != nil {
		return x.Status
	}
	return AuthnDetail_AUTHN_STATUS_UNSPECIFIED
}

func (x *AuthnDetail) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type AuthzDetail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        AuthzDetail_AuthzStatus `protobuf:"varint,1,opt,name=status,proto3,enum=gnsi.acctz.v1.AuthzDetail_AuthzStatus" json:"status,omitempty"`
	Detail        string                  `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzDetail) Reset() {
	*x = AuthzDetail{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzDetail) ProtoMessage() {}

func (x *AuthzDetail) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzDetail.ProtoReflect.Descriptor instead.
func (*AuthzDetail) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{4}
}

func (x *AuthzDetail) GetStatus() AuthzDetail_AuthzStatus {
	if x != nil {
		return x.Status
	}
	return AuthzDetail_AUTHZ_STATUS_UNSPECIFIED
}

func (x *AuthzDetail) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CommandService struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	ServiceType        CommandService_CmdServiceType `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=gnsi.acctz.v1.CommandService_CmdServiceType" json:"service_type,omitempty"`
	Cmd                string                        `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	CmdIstruncated     bool                          `protobuf:"varint,4,opt,name=cmd_istruncated,json=cmdIstruncated,proto3" json:"cmd_istruncated,omitempty"`
	CmdArgs            []string                      `protobuf:"bytes,3,rep,name=cmd_args,json=cmdArgs,proto3" json:"cmd_args,omitempty"`
	CmdArgsIstruncated bool                          `protobuf:"varint,5,opt,name=cmd_args_istruncated,json=cmdArgsIstruncated,proto3" json:"cmd_args_istruncated,omitempty"`
	Authz              *AuthzDetail                  `protobuf:"bytes,6,opt,name=authz,proto3" json:"authz,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommandService) Reset() {
	*x = CommandService{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandService) ProtoMessage() {}

func (x *CommandService) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandService.ProtoReflect.Descriptor instead.
func (*CommandService) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{5}
}

func (x *CommandService) GetServiceType() CommandService_CmdServiceType {
	if x != nil {
		return x.ServiceType
	}
	return CommandService_CMD_SERVICE_TYPE_UNSPECIFIED
}

func (x *CommandService) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *CommandService) GetCmdIstruncated() bool {
	if x != nil {
		return x.CmdIstruncated
	}
	return false
}

func (x *CommandService) GetCmdArgs() []string {
	if x != nil {
		return x.CmdArgs
	}
	return nil
}

func (x *CommandService) GetCmdArgsIstruncated() bool {
	if x != nil {
		return x.CmdArgsIstruncated
	}
	return false
}

func (x *CommandService) GetAuthz() *AuthzDetail {
	if x != nil {
		return x.Authz
	}
	return nil
}

type GrpcService struct {
	state       protoimpl.MessageState      `protogen:"open.v1"`
	ServiceType GrpcService_GrpcServiceType `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=gnsi.acctz.v1.GrpcService_GrpcServiceType" json:"service_type,omitempty"`
	RpcName     string                      `protobuf:"bytes,2,opt,name=rpc_name,json=rpcName,proto3" json:"rpc_name,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/gnsi/acctz/acctz.proto.
	Payloads           []*anypb.Any `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`
	PayloadIstruncated bool         `protobuf:"varint,5,opt,name=payload_istruncated,json=payloadIstruncated,proto3" json:"payload_istruncated,omitempty"`
	Authz              *AuthzDetail `protobuf:"bytes,6,opt,name=authz,proto3" json:"authz,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GrpcService_ProtoVal
	//	*GrpcService_StringVal
	Payload       isGrpcService_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcService) Reset() {
	*x = GrpcService{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcService) ProtoMessage() {}

func (x *GrpcService) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcService.ProtoReflect.Descriptor instead.
func (*GrpcService) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcService) GetServiceType() GrpcService_GrpcServiceType {
	if x != nil {
		return x.ServiceType
	}
	return GrpcService_GRPC_SERVICE_TYPE_UNSPECIFIED
}

func (x *GrpcService) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	return ""
}

// Deprecated: Marked as deprecated in github.com/openconfig/gnsi/acctz/acctz.proto.
func (x *GrpcService) GetPayloads() []*anypb.Any {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *GrpcService) GetPayloadIstruncated() bool {
	if x != nil {
		return x.PayloadIstruncated
	}
	return false
}

func (x *GrpcService) GetAuthz() *AuthzDetail {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *GrpcService) GetPayload() isGrpcService_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GrpcService) GetProtoVal() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*GrpcService_ProtoVal); ok {
			return x.ProtoVal
		}
	}
	return nil
}

func (x *GrpcService) GetStringVal() string {
	if x != nil {
		if x, ok := x.Payload.(*GrpcService_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

type isGrpcService_Payload interface {
	isGrpcService_Payload()
}

type GrpcService_ProtoVal struct {
	ProtoVal *anypb.Any `protobuf:"bytes,7,opt,name=proto_val,json=protoVal,proto3,oneof"`
}

type GrpcService_StringVal struct {
	StringVal string `protobuf:"bytes,8,opt,name=string_val,json=stringVal,proto3,oneof"`
}

func (*GrpcService_ProtoVal) isGrpcService_Payload() {}

func (*GrpcService_StringVal) isGrpcService_Payload() {}

type RecordResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo        *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HistoryIstruncated bool                   `protobuf:"varint,3,opt,name=history_istruncated,json=historyIstruncated,proto3" json:"history_istruncated,omitempty"`
	// Types that are valid to be assigned to ServiceRequest:
	//
	//	*RecordResponse_CmdService
	//	*RecordResponse_GrpcService
	ServiceRequest isRecordResponse_ServiceRequest `protobuf_oneof:"service_request"`
	// Deprecated: Marked as deprecated in github.com/openconfig/gnsi/acctz/acctz.proto.
	Authen        *AuthDetail `protobuf:"bytes,7,opt,name=authen,proto3" json:"authen,omitempty"`
	ComponentName string      `protobuf:"bytes,8,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	TaskIds       []string    `protobuf:"bytes,32,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{7}
}

func (x *RecordResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *RecordResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RecordResponse) GetHistoryIstruncated() bool {
	if x != nil {
		return x.HistoryIstruncated
	}
	return false
}

func (x *RecordResponse) GetServiceRequest() isRecordResponse_ServiceRequest {
	if x != nil {
		return x.ServiceRequest
	}
	return nil
}

func (x *RecordResponse) GetCmdService() *CommandService {
	if x != nil {
		if x, ok := x.ServiceRequest.(*RecordResponse_CmdService); ok {
			return x.CmdService
		}
	}
	return nil
}

func (x *RecordResponse) GetGrpcService() *GrpcService {
	if x != nil {
		if x, ok := x.ServiceRequest.(*RecordResponse_GrpcService); ok {
			return x.GrpcService
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/gnsi/acctz/acctz.proto.
func (x *RecordResponse) GetAuthen() *AuthDetail {
	if x != nil {
		return x.Authen
	}
	return nil
}

func (x *RecordResponse) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *RecordResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type isRecordResponse_ServiceRequest interface {
	isRecordResponse_ServiceRequest()
}

type RecordResponse_CmdService struct {
	CmdService *CommandService `protobuf:"bytes,4,opt,name=cmd_service,json=cmdService,proto3,oneof"`
}

type RecordResponse_GrpcService struct {
	GrpcService *GrpcService `protobuf:"bytes,5,opt,name=grpc_service,json=grpcService,proto3,oneof"`
}

func (*RecordResponse_CmdService) isRecordResponse_ServiceRequest() {}

func (*RecordResponse_GrpcService) isRecordResponse_ServiceRequest() {}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP(), []int{8}
}

func (x *RecordRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_github_com_openconfig_gnsi_acctz_acctz_proto protoreflect.FileDescriptor

const file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDesc = "" +
	"\n" +
	",github.com/openconfig/gnsi/acctz/acctz.proto\x12\rgnsi.acctz.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x04\n" +
	"\vSessionInfo\x12#\n" +
	"\rlocal_address\x18\x01 \x01(\tR\flocalAddress\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\rR\tlocalPort\x12%\n" +
	"\x0eremote_address\x18\x03 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x04 \x01(\rR\n" +
	"remotePort\x12\x19\n" +
	"\bip_proto\x18\x05 \x01(\rR\aipProto\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\tR\tchannelId\x12\x10\n" +
	"\x03tty\x18\a \x01(\tR\x03tty\x12@\n" +
	"\x06status\x18\b \x01(\x0e2(.gnsi.acctz.v1.SessionInfo.SessionStatusR\x06status\x12-\n" +
	"\x04user\x18\t \x01(\v2\x19.gnsi.acctz.v1.UserDetailR\x04user\x120\n" +
	"\x05authn\x18\n" +
	" \x01(\v2\x1a.gnsi.acctz.v1.AuthnDetailR\x05authn\"\xcf\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SESSION_STATUS_LOGIN\x10\x01\x12\x19\n" +
	"\x15SESSION_STATUS_LOGOUT\x10\x02\x12\x17\n" +
	"\x13SESSION_STATUS_ONCE\x10\x03\x12\x19\n" +
	"\x15SESSION_STATUS_ENABLE\x10\x04\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x05\x12\x1c\n" +
	"\x18SESSION_STATUS_OPERATION\x10\x06\"a\n" +
	"\n" +
	"UserDetail\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12#\n" +
	"\rssh_principal\x18\x03 \x01(\tR\fsshPrincipal\"\x91\x02\n" +
	"\n" +
	"AuthDetail\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12'\n" +
	"\x0fprivilege_level\x18\x02 \x01(\rR\x0eprivilegeLevel\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.gnsi.acctz.v1.AuthDetail.AuthenStatusR\x06status\x12\x1d\n" +
	"\n" +
	"deny_cause\x18\x04 \x01(\tR\tdenyCause\"_\n" +
	"\fAuthenStatus\x12\x1d\n" +
	"\x19AUTHEN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTHEN_STATUS_PERMIT\x10\x01\x12\x16\n" +
	"\x12AUTHEN_STATUS_DENY\x10\x02\"\xdb\x03\n" +
	"\vAuthnDetail\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.gnsi.acctz.v1.AuthnDetail.AuthnTypeR\x04type\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.gnsi.acctz.v1.AuthnDetail.AuthnStatusR\x06status\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\"\xc5\x01\n" +
	"\tAuthnType\x12\x1a\n" +
	"\x16AUTHN_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAUTHN_TYPE_NONE\x10\x01\x12\x17\n" +
	"\x13AUTHN_TYPE_PASSWORD\x10\x02\x12\x15\n" +
	"\x11AUTHN_TYPE_SSHKEY\x10\x03\x12\x16\n" +
	"\x12AUTHN_TYPE_SSHCERT\x10\x04\x12\x16\n" +
	"\x12AUTHN_TYPE_TLSCERT\x10\x05\x12\x12\n" +
	"\x0eAUTHN_TYPE_PAP\x10\x06\x12\x13\n" +
	"\x0fAUTHN_TYPE_CHAP\x10\a\"t\n" +
	"\vAuthnStatus\x12\x1c\n" +
	"\x18AUTHN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTHN_STATUS_SUCCESS\x10\x01\x12\x15\n" +
	"\x11AUTHN_STATUS_FAIL\x10\x02\x12\x16\n" +
	"\x12AUTHN_STATUS_ERROR\x10\x03\"\xda\x01\n" +
	"\vAuthzDetail\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.gnsi.acctz.v1.AuthzDetail.AuthzStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"s\n" +
	"\vAuthzStatus\x12\x1c\n" +
	"\x18AUTHZ_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AUTHZ_STATUS_PERMIT\x10\x01\x12\x15\n" +
	"\x11AUTHZ_STATUS_DENY\x10\x02\x12\x16\n" +
	"\x12AUTHZ_STATUS_ERROR\x10\x03\"\xdf\x03\n" +
	"\x0eCommandService\x12O\n" +
	"\fservice_type\x18\x01 \x01(\x0e2,.gnsi.acctz.v1.CommandService.CmdServiceTypeR\vserviceType\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12'\n" +
	"\x0fcmd_istruncated\x18\x04 \x01(\bR\x0ecmdIstruncated\x12\x19\n" +
	"\bcmd_args\x18\x03 \x03(\tR\acmdArgs\x120\n" +
	"\x14cmd_args_istruncated\x18\x05 \x01(\bR\x12cmdArgsIstruncated\x120\n" +
	"\x05authz\x18\x06 \x01(\v2\x1a.gnsi.acctz.v1.AuthzDetailR\x05authz\"\xc1\x01\n" +
	"\x0eCmdServiceType\x12 \n" +
	"\x1cCMD_SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CMD_SERVICE_TYPE_SHELL\x10\x01\x12\x18\n" +
	"\x14CMD_SERVICE_TYPE_CLI\x10\x02\x12\x1a\n" +
	"\x16CMD_SERVICE_TYPE_WEBUI\x10\x03\x12\x1d\n" +
	"\x19CMD_SERVICE_TYPE_RESTCONF\x10\x04\x12\x1c\n" +
	"\x18CMD_SERVICE_TYPE_NETCONF\x10\x05\"\xb5\x04\n" +
	"\vGrpcService\x12M\n" +
	"\fservice_type\x18\x01 \x01(\x0e2*.gnsi.acctz.v1.GrpcService.GrpcServiceTypeR\vserviceType\x12\x19\n" +
	"\brpc_name\x18\x02 \x01(\tR\arpcName\x124\n" +
	"\bpayloads\x18\x03 \x03(\v2\x14.google.protobuf.AnyB\x02\x18\x01R\bpayloads\x12/\n" +
	"\x13payload_istruncated\x18\x05 \x01(\bR\x12payloadIstruncated\x120\n" +
	"\x05authz\x18\x06 \x01(\v2\x1a.gnsi.acctz.v1.AuthzDetailR\x05authz\x123\n" +
	"\tproto_val\x18\a \x01(\v2\x14.google.protobuf.AnyH\x00R\bprotoVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\b \x01(\tH\x00R\tstringVal\"\xc1\x01\n" +
	"\x0fGrpcServiceType\x12!\n" +
	"\x1dGRPC_SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16GRPC_SERVICE_TYPE_GNMI\x10\x01\x12\x1a\n" +
	"\x16GRPC_SERVICE_TYPE_GNOI\x10\x02\x12\x1a\n" +
	"\x16GRPC_SERVICE_TYPE_GNSI\x10\x03\x12\x1b\n" +
	"\x17GRPC_SERVICE_TYPE_GRIBI\x10\x04\x12\x1a\n" +
	"\x16GRPC_SERVICE_TYPE_P4RT\x10\x05B\t\n" +
	"\apayload\"\xc9\x03\n" +
	"\x0eRecordResponse\x12=\n" +
	"\fsession_info\x18\x01 \x01(\v2\x1a.gnsi.acctz.v1.SessionInfoR\vsessionInfo\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x13history_istruncated\x18\x03 \x01(\bR\x12historyIstruncated\x12@\n" +
	"\vcmd_service\x18\x04 \x01(\v2\x1d.gnsi.acctz.v1.CommandServiceH\x00R\n" +
	"cmdService\x12?\n" +
	"\fgrpc_service\x18\x05 \x01(\v2\x1a.gnsi.acctz.v1.GrpcServiceH\x00R\vgrpcService\x125\n" +
	"\x06authen\x18\a \x01(\v2\x19.gnsi.acctz.v1.AuthDetailB\x02\x18\x01R\x06authen\x12%\n" +
	"\x0ecomponent_name\x18\b \x01(\tR\rcomponentName\x12\x19\n" +
	"\btask_ids\x18  \x03(\tR\ataskIdsB\x11\n" +
	"\x0fservice_request\"I\n" +
	"\rRecordRequest\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2[\n" +
	"\x05Acctz\x12R\n" +
	"\x0fRecordSubscribe\x12\x1c.gnsi.acctz.v1.RecordRequest\x1a\x1d.gnsi.acctz.v1.RecordResponse(\x010\x012_\n" +
	"\vAcctzStream\x12P\n" +
	"\x0fRecordSubscribe\x12\x1c.gnsi.acctz.v1.RecordRequest\x1a\x1d.gnsi.acctz.v1.RecordResponse0\x01B\"Z github.com/openconfig/gnsi/acctzb\x06proto3"

var (
	file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescOnce sync.Once
	file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescData []byte
)

func file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDesc), len(file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDesc)))
	})
	return file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDescData
}

var file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_github_com_openconfig_gnsi_acctz_acctz_proto_goTypes = []any{
	(SessionInfo_SessionStatus)(0),     // 0: gnsi.acctz.v1.SessionInfo.SessionStatus
	(AuthDetail_AuthenStatus)(0),       // 1: gnsi.acctz.v1.AuthDetail.AuthenStatus
	(AuthnDetail_AuthnType)(0),         // 2: gnsi.acctz.v1.AuthnDetail.AuthnType
	(AuthnDetail_AuthnStatus)(0),       // 3: gnsi.acctz.v1.AuthnDetail.AuthnStatus
	(AuthzDetail_AuthzStatus)(0),       // 4: gnsi.acctz.v1.AuthzDetail.AuthzStatus
	(CommandService_CmdServiceType)(0), // 5: gnsi.acctz.v1.CommandService.CmdServiceType
	(GrpcService_GrpcServiceType)(0),   // 6: gnsi.acctz.v1.GrpcService.GrpcServiceType
	(*SessionInfo)(nil),                // 7: gnsi.acctz.v1.SessionInfo
	(*UserDetail)(nil),                 // 8: gnsi.acctz.v1.UserDetail
	(*AuthDetail)(nil),                 // 9: gnsi.acctz.v1.AuthDetail
	(*AuthnDetail)(nil),                // 10: gnsi.acctz.v1.AuthnDetail
	(*AuthzDetail)(nil),                // 11: gnsi.acctz.v1.AuthzDetail
	(*CommandService)(nil),             // 12: gnsi.acctz.v1.CommandService
	(*GrpcService)(nil),                // 13: gnsi.acctz.v1.GrpcService
	(*RecordResponse)(nil),             // 14: gnsi.acctz.v1.RecordResponse
	(*RecordRequest)(nil),              // 15: gnsi.acctz.v1.RecordRequest
	(*anypb.Any)(nil),                  // 16: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_github_com_openconfig_gnsi_acctz_acctz_proto_depIdxs = []int32{
	0,  // 0: gnsi.acctz.v1.SessionInfo.status:type_name -> gnsi.acctz.v1.SessionInfo.SessionStatus
	8,  // 1: gnsi.acctz.v1.SessionInfo.user:type_name -> gnsi.acctz.v1.UserDetail
	10, // 2: gnsi.acctz.v1.SessionInfo.authn:type_name -> gnsi.acctz.v1.AuthnDetail
	1,  // 3: gnsi.acctz.v1.AuthDetail.status:type_name -> gnsi.acctz.v1.AuthDetail.AuthenStatus
	2,  // 4: gnsi.acctz.v1.AuthnDetail.type:type_name -> gnsi.acctz.v1.AuthnDetail.AuthnType
	3,  // 5: gnsi.acctz.v1.AuthnDetail.status:type_name -> gnsi.acctz.v1.AuthnDetail.AuthnStatus
	4,  // 6: gnsi.acctz.v1.AuthzDetail.status:type_name -> gnsi.acctz.v1.AuthzDetail.AuthzStatus
	5,  // 7: gnsi.acctz.v1.CommandService.service_type:type_name -> gnsi.acctz.v1.CommandService.CmdServiceType
	11, // 8: gnsi.acctz.v1.CommandService.authz:type_name -> gnsi.acctz.v1.AuthzDetail
	6,  // 9: gnsi.acctz.v1.GrpcService.service_type:type_name -> gnsi.acctz.v1.GrpcService.GrpcServiceType
	16, // 10: gnsi.acctz.v1.GrpcService.payloads:type_name -> google.protobuf.Any
	11, // 11: gnsi.acctz.v1.GrpcService.authz:type_name -> gnsi.acctz.v1.AuthzDetail
	16, // 12: gnsi.acctz.v1.GrpcService.proto_val:type_name -> google.protobuf.Any
	7,  // 13: gnsi.acctz.v1.RecordResponse.session_info:type_name -> gnsi.acctz.v1.SessionInfo
	17, // 14: gnsi.acctz.v1.RecordResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 15: gnsi.acctz.v1.RecordResponse.cmd_service:type_name -> gnsi.acctz.v1.CommandService
	13, // 16: gnsi.acctz.v1.RecordResponse.grpc_service:type_name -> gnsi.acctz.v1.GrpcService
	9,  // 17: gnsi.acctz.v1.RecordResponse.authen:type_name -> gnsi.acctz.v1.AuthDetail
	17, // 18: gnsi.acctz.v1.RecordRequest.timestamp:type_name -> google.protobuf.Timestamp
	15, // 19: gnsi.acctz.v1.Acctz.RecordSubscribe:input_type -> gnsi.acctz.v1.RecordRequest
	15, // 20: gnsi.acctz.v1.AcctzStream.RecordSubscribe:input_type -> gnsi.acctz.v1.RecordRequest
	14, // 21: gnsi.acctz.v1.Acctz.RecordSubscribe:output_type -> gnsi.acctz.v1.RecordResponse
	14, // 22: gnsi.acctz.v1.AcctzStream.RecordSubscribe:output_type -> gnsi.acctz.v1.RecordResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_gnsi_acctz_acctz_proto_init() }
func file_github_com_openconfig_gnsi_acctz_acctz_proto_init() {
	if File_github_com_openconfig_gnsi_acctz_acctz_proto != nil {
		return
	}
	file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[6].OneofWrappers = []any{
		(*GrpcService_ProtoVal)(nil),
		(*GrpcService_StringVal)(nil),
	}
	file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes[7].OneofWrappers = []any{
		(*RecordResponse_CmdService)(nil),
		(*RecordResponse_GrpcService)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDesc), len(file_github_com_openconfig_gnsi_acctz_acctz_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_github_com_openconfig_gnsi_acctz_acctz_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_gnsi_acctz_acctz_proto_depIdxs,
		EnumInfos:         file_github_com_openconfig_gnsi_acctz_acctz_proto_enumTypes,
		MessageInfos:      file_github_com_openconfig_gnsi_acctz_acctz_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_gnsi_acctz_acctz_proto = out.File
	file_github_com_openconfig_gnsi_acctz_acctz_proto_goTypes = nil
	file_github_com_openconfig_gnsi_acctz_acctz_proto_depIdxs = nil
}
